config/routes.rb
Rails.application.routes.draw do
  root 'searches#new'
  resources :books
  resources :categories
  resources :searches, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category

  validates :title, presence: true
  validates :description, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/search.rb
class Search < ApplicationRecord
  def search_book
    book = Book.all 

    book = book.where(['title LIKE :title OR description Like :title', title: "%#{title}%",  title: "%#{title}%"]) if title.present?
    book = book.where(category_id: category_id) if category_id.present?

    return book
end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :current_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
    @categories = Category.all
  end

  def create
    @book = Book.create(book_params)
    if @book.save
      redirect_to new_search_path
    else 
      render :new
    end
  end 

  def edit
    # @book = Book.find(params[:id])
    @categories = Category.all
  end

  def update
    # @book = Book.find(params[:id])
     if @book.update(book_params)
      redirect_to book_path(@book), notice: "ブックの編集成功しました。"
    else 
      render　:edit
    end
  end

  def destroy
    # @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :category_id)
  end

  def current_book
    @book = Book.find(params[:id])
    unless @book
      redirect_to new_search_path, notice: "探しているブックがありません。"
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :current_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def edit
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)

    redirect_to categories_path
  end 

  def update
    @category.update(category_params)

    redirect_to categories_path
  end

  def destroy
    @category.destroy

    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def current_category
    @category = Category.find(params[:id])
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @search = Search.find(params[:id])
  end 

  def new 
    @search = Search.new
    @categories = Category.all
    @category_id = Book.distinct.pluck(:category_id)
  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end 

  private

  def search_params
    params.require(:search).permit(:title, :description, :category_id)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/books/edit.html.erb
<div class="books_form">
  <h1>ブック</h1>
  <%= form_with model: @book, local: true  do |f| %>
    <%= f.text_field :title, class: "title-input"  %>
    <%= f.collection_select(:category_id, @categories, :id, :name, {class: "title-input"}) %>
    <%= f.text_area :description, size: "20x10",class: "title-input text-area" %>
</div>
    <%= f.submit "編集", class: 'button' %>
  <% end %>

<%= link_to "戻る", :back, class: 'back_button' %>

app/views/books/index.html.erb
<div class="books_form">
  <h2>ブック一覧表</h2>
  <% @books.each do |book| %>
    <div class="books_lists">
      <%= book.title %></td>
      <div class="books_lists_button">
        <%= link_to '編集', edit_book_path(book), method: 'get', class: "form_button"%></td>
        <%= link_to '削除', book_path(book), method: :delete, data: { confirm: '削除してもよろしいですか?' }, class: "form_button delete" %></td>
      </div>
    </div>
  <% end %>
</div>
<%= link_to "ホームページへ", new_search_path, class: 'button' %>

app/views/books/new.html.erb
<%= form_with model: @book, local: true  do |f| %>
  <div class="books_form">
    <h1>新しい本の登録</h1>
      <%= f.text_field :title, placeholder: "タイトルを入力してください。", class: "title-input" %>
      <%= f.collection_select(:category_id, @categories, :id, :name, {prompt: "カテゴリーを選択してください"}, {class: "title-input"}) %>
      <%= f.text_area :description,size: "20x10", placeholder: "概要を入力してください。", class: "title-input text-area" %>
  </div>

    <%= f.submit "登録", class: 'button'  %>
  <% end %>

<%= link_to "戻る", :back, class: 'back_button' %>

app/views/books/show.html.erb
<div class="books_form">
  <div class="show_books">
    <h3>タイトル</h3>
    <p><%= @book.title %></p>
  </div>
  <div class="show_books">
    <h3>カテゴリー</h3>
    <p><%= @book.category.name %></p>
  </div>
  <div class="show_books">
    <h3>詳細</h3>
    <p><%= @book.description %></p>
  </div>
</div>

<%= link_to "ホームページへ", new_search_path, class: 'button' %>

app/views/categories/edit.html.erb
<%= form_with model: @category, local: true do |f| %>
  <div class="category-form">
    <h2>カテゴリー</h2>

    <%= f.text_field :name, placeholder: "カテゴリー名を入力してください。",class: "title-input"  %>
  </div>

  <%= f.submit "変更", class: "button" %>
<% end %>

<%= link_to "戻る", :back, class: 'back_button' %>

app/views/categories/index.html.erb
<div class="category-form">
  <h2 class="title-list">カテゴリー一覧</h2>
  <%= link_to "", new_category_path, class: "fa fa-plus-circle fa-2x icon-plus", aria: { hidden: "true" } %>
  <% @categories.each do |category| %>
    <div class="category-lists">
      <%= category.name %>
      <div class="category-lists-button">
        <%= link_to '編集', edit_category_path(category), method: 'get', class: "form_button"%>
        <%= link_to '削除', category_path(category), method: :delete, data: { confirm: '削除してもよろしいですか?' }, class: "form_button delete" %>
      </div>
    </div>
  <% end %>
</div>
<%= link_to "ホームページへ", new_search_path, class: 'button' %>

app/views/categories/new.html.erb
<%= form_with model: @category, local: true do |f| %>
  <div class="category-form">
    <h2>新しい本の登録</h2>
    <%= f.text_field :name, placeholder: "カテゴリー名を入力してください。",class: "title-input"  %>
  </div>

  <%= f.submit "登録", class: "button" %>
<% end %>

<%= link_to "戻る", :back, class: 'back_button' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link
      href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&display=swap"
      rel="stylesheet"
    />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/new.html.erb
<div class="container">
  <nav class="navbar">
    <div>
      <ul>
        <li>
          <%= link_to "", new_book_path, class: "fa fa-plus-circle fa-2x", aria: { hidden: "true" } %>
        </li>
        <li>
          <%= link_to "", books_path, class: "fa fa-book fa-2x", aria: { hidden: "true" }%>
        </li>
        <li>
          <%= link_to "", categories_path, class: "fa fa-list fa-2x", aria: { hidden: "true" }%>
        </li>
      </ul>
    </div>
  </nav>
    
  <main>  
    <%= form_with model: @search, local: true  do |f| %>
      <div class="search-form">
        <h2>ブック検索</h2>
        <%= f.text_field :title, class: "title-input"%>
      </div>
      <div class="form-radio-input">
        <%= f.collection_radio_buttons(:category_id, @categories, :id, :name, {prompt: "カテゴリーを選択してください"}, class: "radio-input") %>
      </div>

      <%= f.submit "検索", class:"button" %>
    <% end %>
  </main>
</div>

app/views/searches/show.html.erb
<div class="category-form">
  <h2>検索結果</h2>
  
  <% if @search == nil ||
    @search.search_book.empty? %>
    <p class="search-empty">検索した本はありません。</p>
  <% else %>
  <table>
    <thead>
      <tr>
        <th>タイトル</th>
        <th>カテゴリー</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @search.search_book.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.category.name %></td>
          <td><%= link_to 'Show', book, class: 'form_button' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>


<p><%= link_to "ホームページへ", new_search_path, class: 'button' %></p>